[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
xenblocks_airdrop_tracker = "xen8pjUWEnRbm1eML9CGtHvmmQfruXMKUybqGjn3chv"

[programs.testnet]
delegation_program = "xen8pjUWEnRbm1eML9CGtHvmmQfruXMKUybqGjn3chv"

[programs.mainnet]
xenblocks_airdrop_tracker = "xen8pjUWEnRbm1eML9CGtHvmmQfruXMKUybqGjn3chv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
deploy = "anchor deploy"
deploy-localnet = "anchor deploy --provider.cluster http://localhost:8899 --program-id target/deploy/delegation_program-keypair-localnet.json"
deploy-testnet = "anchor deploy --provider.cluster https://rpc.testnet.x1.xyz --program-id target/deploy/delegation_program-keypair-testnet.json"
test = "bun vitest run --config vitest.config.anchor.ts"
